### ISSUE TITLE
Issue with minio-operator creation

### ISSUE THREAD

**Issue by Peyoz** [minio/minio-operator#112]
Hi Guys,

with the last yaml definition for the minio-operator, I got this issue

```
[root@cloumgmt minio]# curl -O https://raw.githubusercontent.com/minio/minio-operator/master/minio-operator.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3477  100  3477    0     0  10683      0 --:--:-- --:--:-- --:--:-- 10665
[root@cloumgmt minio]# kubectl apply -f minio-operator.yaml 
customresourcedefinition.apiextensions.k8s.io/minioinstances.operator.min.io unchanged
customresourcedefinition.apiextensions.k8s.io/mirrorinstances.operator.min.io unchanged
clusterrole.rbac.authorization.k8s.io/minio-operator-role unchanged
serviceaccount/minio-operator-sa unchanged
The ClusterRoleBinding "minio-operator-binding" is invalid: subjects[0].namespace: Required value
```

This is on a freshly installed RKE cluster.
There is something missing in the namespace scopes I suppose.

Let me know if you need any logs / output.

Cheers!

**Comment by vmwiz** [comment]
Caused by 67a1c4f68a16eb822e4609abc3062ee671068ecb `Remove fixed namespace from install`

The `ServiceAccount` subject is no more scoped in the `ClusterRoleBinding` definition.

Quickfix:
```
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: minio-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-role
subjects:
- kind: ServiceAccount
  name: minio-operator-sa
  namespace: __yournamespacegohere__
```
@dvaldivia wouldn't it be better to let the namespace fixed in the plain yaml and let the user override it with `kustomize` ?
