### ISSUE TITLE
Missing mcs metadata definitions in MinIOInstance crd

### ISSUE THREAD

**Issue by vmwiz** [minio/minio-operator#125]
## Expected Behavior

The `MinIOInstance` ressource object must keep `spec.mcs.metadata.labels` and `spec.mcs.selector.matchLabels` values from applied yaml

## Current Behavior

Both values are missing from the `MinIOInstance` object after applying the `minioinstance-mcs.yaml` example.

_Might be_ the reason why I cannot get MCS deployed too with the example. (haven't yet troubleshooted this one) 

## Possible Solution

Add in the `MinIOInstance` crd schema both fields
```
...
                mcs:
                  ...
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          properties:
                            app:
                              type: string
                    selector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          properties:
                            app:
                              type: string
```
## Steps to Reproduce (for bugs)

1. Deploy the operator 
`kustomize build . | kubectl apply -f minio-operator.yaml -`
2. Deploy the MCS minio instance example 
`kubectl apply -n minio -f minioinstance-mcs.yaml`
3. Display the resulting `MinIOInstance`object and look for the `mcs:` definition
```
kubectl -n minio get minioinstance minio -o jsonpath={.spec.mcs}

map[image:minio/mcs:v0.0.4 mcsSecret:map[name:minio-mcs-secret] replicas:2]
```
Both `metadata` and `selector` fields are missing from the output.

## Context

While trying to deploy a minio instance with mcs using ArgoCD the `MinIOInstance` object stays `OutOfSync` ; looking at the diffs ArgoCD tries to re-apply constantly the missing fields.

## Your Environment

* Version used (`minio-operator`): 2.0.2
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes v1.16.9
* Server type and version: VMware vSphere VMs
* Operating System and version (`uname -a`): `Linux k8s-master-0 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your deployment file: N/A
