### ISSUE TITLE
Create local PV and storage class in operator.

### ISSUE THREAD

**Issue by fanux** [minio/minio-operator#131]
I think user create PV and storage class is unfriendly, operator should do it.
```
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: minio 
  localPV:
      nodes:
      - label: kubernetes.io/hostname=iz2ze28yw4rvtf8qen35kyz
         dataDir: /data
         storageClassName: minio
```
Operator can run a job on node to create data dir, then create PVs.
