### ISSUE TITLE
MinIO upgrade can cause lack of read/write quorum

### ISSUE THREAD

**Issue by kalinon** [minio/minio-operator#136]
## Context
I am unsure how to properly write up this issue, as it seems to involve a few different things. The current operator does not update your `StatefulSet` when you change the image tag in the defined `MinIOInstance`. This may be intentional, but i can make a separate bug case for it if needed. So the current method i have been using to make changes to my `StatefulSet` is to delete the `MinIOInstance` and re-create it with the changes I want/need. This is important to call out in the following scenario.

Timeline of events:

1. Need to replace two drives (2/7)
2. Delete MinIOInstance to take down statefulset
3. Decide its a great idea to update the minio image to `RELEASE.2020-06-01T17-28-03Z`
4. Replace the PV of the 2 drives
5. Recreate MinIOInstance

At this point all the services come up and try to upgrade, but none have a quorum and continuously throw:

```
 minio-5:Waiting for all MinIO sub-systems to be initialized.. lock acquired
 minio-5:Attempting encryption of all config, IAM users and policies on MinIO backend
 minio-5:Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)
```

Process I performed to fix it:

1. create format.json on new disks
2. Revert back to original minio version: `RELEASE.2020-05-16T01-33-21Z`
2. delete backend-encrypted on each existing disk
3. recreate users/iam

Thread on MinIO Slack: https://minio.slack.com/archives/C3NDUB8UA/p1591206779499800
Versions upgraded from -> to: `RELEASE.2020-05-16T01-33-21Z` -> `RELEASE.2020-06-01T17-28-03Z`

## Expected Behavior

Changing the image should safely upgrade the image of statefulset and safely upgrade the minio deployment to the new version.

## Current Behavior

The current official method of updating is to call the `mc update` command. However, part of the upgrade process is each server replaces its binary with a new version and restarts. Seeing as we are in a containerized deployment.... changes would go away.

Causing configs to be encrypted at different versions, then leading to a lack of quorum and well.. no access to minio

## Possible Solution

Perhaps update the statefulset and perform a slow rolling restart to all nodes?

## Regression

No

## Your Environment
* Version used (`minio-operator`): minio/k8s-operator:2.0.3
* Environment name and version (e.g. kubernetes v1.17.2): v1.17.5
* Server type and version: Distributed - RELEASE.2020-05-16T01-33-21Z
* Operating System and version (`uname -a`): Linux kube-02 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

```yaml
apiVersion: operator.min.io/v1
kind: MinIOInstance
metadata:
  name: minio
## If specified, MinIOInstance pods will be dispatched by specified scheduler.
## If not specified, the pod will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler
spec:
  selector:
    matchLabels:
      kalinon.com/app: minio
      kalinon.com/function: server
  ## Add metadata to the all pods created by the StatefulSet
  metadata:
    labels:
      kalinon.com/app: minio
      kalinon.com/function: server
      kalinon.com/prometheus.scrape: minio
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
      sidecar.istio.io/inject: "false"
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2020-05-16T01-33-21Z
  ## A ClusterIP Service will be created with the given name
  serviceName: minio-internal-service
  ## Secret with credentials to be used by MinIO instance.
  credsSecret:
    name: minio-creds-secret
  zones:
    - name: "zone-0"
      ## Number of MinIO servers/pods in this zone.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      servers: 7
  ## Supply number of volumes to be mounted per MinIO server instance.
  volumesPerServer: 1
  ## Mount path where PV will be mounted inside container(s). Defaults to "/export".
  mountPath: /export
  ## Sub path inside Mount path where MinIO starts. Defaults to "".
  # subPath: /data
  ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO cluster.
  ## Please do not change the volumeClaimTemplate field while expanding the cluster, this may
  ## lead to unbound PVCs and missing data
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  ## Define configuration for MCS (Graphical user interface for MinIO)
  mcs:
    image: minio/mcs:latest
    mcsAccessKey: "mcs"
    mcsSecret:
      name: minio-mcs-secret
    metadata:
      labels:
        app: mcs # Should match spec.mcs.selector.matchLabels
    selector:
      matchLabels:
        app: mcs # Should match spec.mcs.metadata.labels
  ## Secret with certificates to configure TLS for MinIO certs. Create secrets as explained
  ## here: https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  # name: tls-ssl-minio
  ## Enable Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false
  ## PodManagement policy for pods created by StatefulSet. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details. Defaults to "Parallel"
  ## If set to "OrderedReady", then disable Readiness checks below. Readiness check will only
  ## work if PodManagementPolicy is set to "Parallel".
  podManagementPolicy: Parallel
  ## Used when "requestAutoCert" is set to true. Set CommonName for the auto-generated certificate.
  ## Internal DNS name for the pod will be used if CommonName is not provided.
  ## DNS name format is minio-{0...3}.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  ## Used to specify a toleration for a pod
  tolerations:
   - effect: NoSchedule
     key: plex-only
     operator: Equal
     value: "true"
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
    - name: MINIO_BROWSER
      value: "on"
    - name: MINIO_STORAGE_CLASS_RRS
      value: "EC:2"
    - name: MINIO_STORAGE_CLASS_STANDARD
      value: "EC:3"
    - name: MINIO_REGION_NAME
      value: us-east-1
    - name: MINIO_DISK_USAGE_CRAWL_DEBUG
      value: "on"
  ## Configure resource requests and limits for MinIO containers
  resources:
    requests:
      memory: 2Gi
      cpu: 250m
  ## Liveness probe detects situations where MinIO server instance
  ## is not working properly and needs restart. Kubernetes automatically
  ## restarts the pods if liveness checks fail.
  liveness:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 60
  ## Readiness probe detects situations when MinIO server instance
  ## is not ready to accept traffic. Kubernetes doesn't forward
  ## traffic to the pod while readiness checks fail.
  ## Readiness check will only work if PodManagementPolicy is set to "Parallel".
  ## Disable this check if you're setting PodManagementPolicy to "OrderedReady".
  readiness:
    httpGet:
      path: /minio/health/ready
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 60
  ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
  ## eligible to run on a node, the node must have each of the
  ## indicated key-value pairs as labels.
  ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  # nodeSelector:
  #   disktype: ssd
  ## Affinity settings for MinIO pods. Read more about affinity
  ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
  # affinity:
```
