### ISSUE TITLE
Add custom tolerations to the statefulsets

### ISSUE THREAD

**Issue by anthonyhaussman** [minio/minio-operator#42]
Please, can you add support for the following field in the statefulset to be available for configuration in the minioinstance CRD.

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: storage
```

Thanks.
