### ISSUE TITLE
Dynamic PVC using storageclass fails because name is nill

### ISSUE THREAD

**Issue by piwi91** [minio/minio-operator#47]
Requesting a new MinIO instance with a dynamic PVC doesn't work with the given example in this repository. You need to define the `name` in the `volumeClaimTemplate` and in the `volumeClaimTemplate.metadata` to get it working otherwise you'll get the following error in the generated statefullset:

```
Events:
  Type     Reason        Age                From                    Message
  ----     ------        ----               ----                    -------
  Warning  FailedCreate  1s (x12 over 11s)  statefulset-controller  create Claim -minio-0 for Pod minio-0 in StatefulSet minio failed error: PersistentVolumeClaim "-minio-0" is invalid: metadata.name: Invalid value: "-minio-0": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  Warning  FailedCreate  1s (x12 over 11s)  statefulset-controller  create Pod minio-0 in StatefulSet minio failed error: Failed to create PVC -minio-0: PersistentVolumeClaim "-minio-0" is invalid: metadata.name: Invalid value: "-minio-0": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

This is because the `name` is `nill`:

```
$ kubectl describe statefulset minio

Name:               minio
Namespace:          default
CreationTimestamp:  Fri, 11 Oct 2019 16:12:34 +0200
Selector:           v1beta1.min.io/instance=minio                                                                                                                                                                                                            Labels:             <none>
Annotations:        <none>                                                                                                                                                                                                                                   Replicas:           2 desired | 0 total                                                                                                                                                                                                                      Update Strategy:    RollingUpdate                                                                                                                                                                                                                            Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed                                                                                                                                                                                           Pod Template:                                                                                                                                                                                                                                                  Labels:       app=minio                                                                                                                                                                                                                                                    v1beta1.min.io/instance=minio                                                                                                                                                                                                                  Annotations:  prometheus.io/path: /minio/prometheus/metrics                                                                                                                                                                                                                prometheus.io/port: 9000                                                                                                                                                                                                                                     prometheus.io/scrape: true                                                                                                                                                                                                                     Containers:                                                                                                                                                                                                                                                   minio:                                                                                                                                                                                                                                                        Image:      minio/minio:RELEASE.2019-10-11T00-38-09Z                                                                                                                                                                                                         Port:       9000/TCP                                                                                                                                                                                                                                         Host Port:  0/TCP                                                                                                                                                                                                                                            Args:                                                                                                                                                                                                                                                          server                                                                                                                                                                                                                                                       http://minio-0.minio-hl-svc.default.svc.cluster.local/export                                                                                                                                                                                                 http://minio-1.minio-hl-svc.default.svc.cluster.local/export                                                                                                                                                                                               Requests:                                                                                                                                                                                                                                                      cpu:     250m                                                                                                                                                                                                                                                memory:  512Mi                                                                                                                                                                                                                                             Liveness:  http-get http://:9000/minio/health/live delay=120s timeout=1s period=20s #success=1 #failure=3                                                                                                                                                    Environment:                                                                                                                                                                                                                                                   MINIO_BROWSER:     on                                                                                                                                                                                                                                        MINIO_ACCESS_KEY:  <set to the key 'accesskey' in secret 'minio-creds-secret'>  Optional: false                                                                                                                                                              MINIO_SECRET_KEY:  <set to the key 'secretkey' in secret 'minio-creds-secret'>  Optional: false                                                                                                                                                            Mounts:                                                                                                                                                                                                                                                        /export from  (rw)                                                                                                                                                                                                                                       Volumes:  <none>                                                                                                                                                                                                                                           Volume Claims:                                                                                                                                                                                                                                                 Name:                                                                                                                                                                                                                                                        StorageClass:  csi-archive                                                                                                                                                                                                                                   Labels:        <none>                                                                                                                                                                                                                                        Annotations:   <none>                                                                                                                                                                                                                                        Capacity:      10Gi                                                                                                                                                                                                                                          Access Modes:  [ReadWriteOnce]
```

The MinIOInstance below works:

```yaml
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
spec:
  ## Add metadata to the pods created by the StatefulSet
  metadata:
    labels:
      app: minio
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2019-10-11T00-38-09Z
  ## Secret with credentials to be used by MinIO instance.
  credsSecret:
    name: minio-creds-secret
  ## Supply number of replicas.
  ## For standalone mode, supply 1. For distributed mode, supply 4 or more (should be even).
  ## Note that the operator does not support upgrading from standalone to distributed mode.
  replicas: 2
  ## PodManagement policy for pods created by StatefulSet. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details. Defaults to "Parallel"
  podManagementPolicy: Parallel
  ## Enable Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false
  ## Used when "requestAutoCert" is set to true. Set CommonName for the auto-generated certificate.
  ## Internal DNS name for the pod will be used if CommonName is not provided.
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []

  ## Used to specify a toleration for a pod
  #tolerations:
  #  - effect: NoSchedule
  #    key: dedicated
  #    operator: Equal
  #    value: storage
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
    - name: MINIO_BROWSER
      value: "on"
    # - name: MINIO_STORAGE_CLASS_RRS
    #   value: "EC:2"
  ## Configure resource requests and limits for MinIO containers
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
  ## Liveness probe detects situations where MinIO server instance
  ## is not working properly and needs restart. Kubernetes automatically
  ## restarts the pods if liveness checks fail.
  liveness:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 20
  ## Readiness probe detects situations when MinIO server instance
  ## is not ready to accept traffic. Kubernetes doesn't forward
  ## traffic to the pod while readiness checks fail.
  ## Recommended to be used only for standalone MinIO Instances. (replicas = 1)
  # readiness:
  #   httpGet:
  #     path: /minio/health/ready
  #     port: 9000
  #   initialDelaySeconds: 120
  #   periodSeconds: 20
  ## Affinity settings for MinIO pods. Read more about affinity
  ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
  # affinity:
  ## Secret with certificates to configure TLS for MinIO certs. Create secrets as explained
  ## here: https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  # name: tls-ssl-minio
  ## Mountpath where PV will be mounted inside container(s). Defaults to "/export".
  # mountPath: /export
  ## Subpath inside Mountpath where MinIO starts. Defaults to "".
  # subPath: /data
  volumeClaimTemplate:
    name: data
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: csi-archive
```
