### ISSUE TITLE
Allow `externalCertSecret` to be of type `kubernetes.io/tls`

### ISSUE THREAD

**Issue by voidengineer** [minio/minio-operator#49]
At the moment minio-operator expects the `externalCertSecret` to have the keys `public.crt` and `private.key`.

Kubernetes has a specific kind of secrets with the type `kubernetes.io/tls`, which have the keys `ca.crt`, `tls.crt` and `tls.key`. This kind of secret is even generated by tool like [cert-manager](https://github.com/jetstack/cert-manager).

It would be great, if minio-operator could support those secrets, maybe by adding a new field named `type` under `externalCertSecret`:

```yaml
spec:
  externalCertSecret:
    name: my-example-minio-service-tls
    type: kubernetes.io/tls
```

**Comment by nitisht** [comment]
we'll take a look @voidengineer

**Comment by nitisht** [comment]
This is fixed by #64

**Comment by mostafa8026** [comment]
I'm currently using externalCert to use cert-manager, my config is:
```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: tenant-min3
  namespace: min3
scheduler:
  name: ""
spec:
  certConfig: {}
  externalCertSecret:
  - name: tls-minio
    type: cert-manager.io/v1alpha2
  console:
    consoleSecret:
      name: tenant-min3-console-secret
    image: minio/console:v0.4.6
    metadata:
      creationTimestamp: null
      name: tenant-min3
    replicas: 2
    resources: {}
  credsSecret:
    name: tenant-min3-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: tenant-min3-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: default
      status: {}
    volumesPerServer: 4
status:
  availableReplicas: 0
  currentState: ""
```
but I got this error:
```

  Warning  FailedMount  106s (x12 over 9m59s)  kubelet            MountVolume.SetUp failed for volume "tenant-min3-tls" : references non-existent secret key: ca.crt
  Warning  FailedMount  70s                    kubelet            Unable to attach or mount volumes: unmounted volumes=[tenant-min3-tls], unattached volumes=[tenant-min3-tls default-token-xh4js 0 1 2 3]: timed out waiting for the condition

```
my cert-config is:

```
   apiVersion: cert-manager.io/v1
   kind: Issuer
   metadata:
     name: letsencrypt-staging
     namespace: min3
   spec:
     acme:
       # The ACME server URL
       server: https://acme-staging-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: mostafa_issuer@isseuring.com
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: letsencrypt-staging
       # Enable the HTTP-01 challenge provider
       solvers:
       - http01:
           ingress:
             class:  nginx
```
and ingress config is:
```

kind: Ingress
metadata:
  name: min3
  namespace: min3
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-staging"

spec:
  tls:
  - hosts:
    - mystorage.com
    secretName: tls-minio
  rules:
  - host: mystorage.com
    http:
      paths:
      - path: /
        backend:
          serviceName: minio
          servicePort: 80
```

**Comment by JannikZed** [comment]
got the same issue with cert-manager; `MountVolume.SetUp failed for volume "XXX-tls" : references non-existent secret key: public.crt`

**Comment by mostafa8026** [comment]
You have to remove the external-cert specification from your tenant config. I have this problem before and It was resolved with correcting the metadata section of ingress configuration in this way:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-minio
  namespace: min3
  annotations:
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

```

I recommend you to read [ingress documentation](https://kubernetes.github.io/ingress-nginx/), there was plenty of useful information.
