### ISSUE TITLE
able to delete file w/o login in minio browser

### ISSUE THREAD

**Issue by andypeng2015** [minio/minio-operator#58]
I am able to delete backup file without login, even though I already configured secret for login, as shwon below

<img width="1284" alt="minio" src="https://user-images.githubusercontent.com/24508594/71498853-05c31600-2899-11ea-9690-21f39b6c20a0.png">

```
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
spec:
  metadata:
    labels:
      app: minio
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2019-10-12T01-39-57Z
  ## Secret with credentials to be used by MinIO instance.
  credsSecret:
    name: minio-creds-secret
```

```
spec:
      serviceAccountName: minio-operator-sa
      containers:
        - name: minio-operator
          image: minio/k8s-operator:1.0.4
          imagePullPolicy: IfNotPresent
```
