### ISSUE TITLE
Document how to use multiple volumes per node

### ISSUE THREAD

**Issue by garyedwards** [minio/minio-operator#76]
I am looking to set up minio-operator in standalone mode with 4 disks.  I can not find the documentation / best practice for attaching multiple drives. I see that `/export` is where a single PV may be mounted but how do I tell the operator that I have multiple?

Thanks a lot in advance.

**Comment by garyedwards** [comment]
Hi Just a quick update.

When I do a volume claim for a single drive as per your documentation the pvc is created and minio works as expected.

``` yaml
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: local-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```

When I add a number of over volume claims that I would be expected to be handled by the operator and volumes to be created in the correct locations no pvcs are created and the operator creates an pod with no volumes attached.

``` yaml
  volumeClaimTemplates:
  - metadata:
      name: data1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      selector:
        matchLabels:
          diskUuid: 5d27cf1d-09e8-4354-8df2-f7b536d31867
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: data2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      selector:
        matchLabels:
          diskUuid: 517e80fc-6d72-457f-a3ca-2d816c21e8bb
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: data3
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      selector:
        matchLabels:
          diskUuid: 00af6255-14b4-4d92-b077-f326998b7b13
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: data4
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      selector:
        matchLabels:
          diskUuid: 9b59d1e0-3c4f-4e4a-b341-8d9d6c4b7b02
      resources:
        requests:
          storage: 1Gi
```

Maybe the operator only expects one disk per pod?  Thanks again.
