### ISSUE TITLE
rbac issue with latest

### ISSUE THREAD

**Issue by cameronbraid** [minio/minio-operator#91]
minio operator pod reports :

```
E0501 06:07:52.821618       1 reflector.go:134] k8s.io/client-go@v0.0.0-20181016014101-70926af6e803/tools/cache/reflector.go:95: Failed to list *v1beta1.MinIOInstance: minioinstances.miniocontroller.min.io is forbidden: User "system:serviceaccount:minio:minio-operator-sa" cannot list resource "minioinstances" in API group "miniocontroller.min.io" at the cluster scope

```

**Comment by cameronbraid** [comment]
works if I use `https://raw.githubusercontent.com/minio/minio-operator/1.0.9/minio-operator.yaml` instead of master

**Comment by dvaldivia** [comment]
@cameronbraid you can fix this by adding the following permission to the latest `minio-operator-role`
```
- apiGroups:
  - min.io
  resources:
  - "*"
  verbs:
  - "*"
```

**Comment by sunsingerus** [comment]
Still facing the same issue:
```
E0514 17:35:17.291403       1 reflector.go:134] k8s.io/client-go@v0.0.0-20181016014101-70926af6e803/tools/cache/reflector.go:95: Failed to list *v1beta1.MinIOInstance: minioinstances.miniocontroller.min.io is forbidden: User "system:serviceaccount:minio-operator-ns:minio-operator-sa" cannot list resource "minioinstances" in API group "miniocontroller.min.io" at the cluster scope
```

and above mentioned section
```
- apiGroups:
  - min.io
  resources:
  - "*"
  verbs:
  - "*"
```
is in place

**Comment by sunsingerus** [comment]
by the way, after changing cluster role to `cluster-admin`
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
face the another error:
```
E0514 17:29:01.120975       1 reflector.go:134] k8s.io/client-go@v0.0.0-20181016014101-70926af6e803/tools/cache/reflector.go:95: Failed to list *v1beta1.MinIOInstance: the server could not find the requested resource (get minioinstances.miniocontroller.min.io)
```
